# Generated by Django 5.0.1 on 2024-03-30 17:12

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.custom_upload_to),
        ),
    ]
