# Generated by Django 5.0.1 on 2024-03-30 17:12

import appmodels.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=5000, null=True)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('pic', models.ImageField(blank=True, null=True, upload_to=appmodels.models.upload_to_blog_pics)),
                ('url', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('public', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='Easy Regional Block', max_length=100)),
                ('app_syncopation', models.CharField(default='ERB', max_length=10)),
                ('app_logs', models.CharField(default='1', max_length=1)),
                ('app_url', models.CharField(default='https://app.tfgibex.com/', max_length=100)),
                ('smtp_email_account', models.CharField(default='no-reply@tfgibex.com', max_length=100, blank=True, null=True)),
                ('smtp_password', models.CharField(default='app2024ERB/', max_length=100, blank=True, null=True)),
                ('smtp_server', models.CharField(default='smtp.servidor-correo.net', max_length=100, blank=True, null=True)),
                ('smtp_port', models.IntegerField(default=587)),
                ('app_primary', models.CharField(default='#2A3F54', max_length=9)),
                ('app_color_1', models.CharField(default='#03586A', max_length=9)),
                ('app_color_2', models.CharField(default='#1F6B7B', max_length=9)),
                ('app_color_3', models.CharField(default='#3B7D8B', max_length=9)),
                ('app_color_4', models.CharField(default='#57909C', max_length=9)),
                ('app_color_5', models.CharField(default='#73A2AC', max_length=9)),
                ('app_color_6', models.CharField(default='#8FB5BD', max_length=9)),
                ('app_color_7', models.CharField(default='#ABC7CD', max_length=9)),
                ('app_color_8', models.CharField(default='#C7DADE', max_length=9)),
                ('app_success', models.CharField(default='#41A91A', max_length=9)),
                ('app_danger', models.CharField(default='#A91A1A', max_length=9)),
                ('app_icon', models.CharField(default='fa-solid fa-angles-right', max_length=100)),
                ('app_transparency_factor', models.CharField(default='61', max_length=2)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR')], default='USD', max_length=3)),
                ('paypal_client_id', models.CharField(default='Adeu-0NRZJYyAF3uv4-N8v72r2b5nwBlAqCQxXuIJIlhwvGNF9t8zZMphHVDKynnqYmj6dPAiAoPAT5Q', max_length=100)),
                ('paypal_secret_key', models.CharField(default='EOa5rhZiJMHlb17CzogGSmx24nLcNg6wse6ENYk2PAebJXGlxG_RhKb--0cFR8Ec5kY7DmBMOUMjj4kZ', max_length=100)),
                ('paypal_account_email', models.CharField(default='sb-nz6pt29186337@business.example.com', max_length=100)),
                ('google_oauth_client_id', models.CharField(blank=True, max_length=100, null=True)),
                ('google_oauth_client_secret', models.CharField(blank=True, max_length=100, null=True)),
                ('google_analytics_tag_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('price', models.FloatField(default=0)),
                ('interval_count', models.IntegerField(default=1)),
                ('interval_unit', models.CharField(choices=[('Y', 'Year'), ('M', 'Month'), ('W', 'Week')], default='M', max_length=3)),
                ('discount', models.IntegerField(default=0)),
                ('public', models.BooleanField(default=True)),
                ('stripe_subscription_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('paypal_subscription_id', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurgeryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurgicalArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.IntegerField(default=0)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_method', models.CharField(choices=[('Free', 'Free'), ('Paypal', 'Paypal'), ('Cash', 'Cash'), ('Bank transfer', 'Bank transfer'), ('Other', 'Other')], default='Free', max_length=20)),
                ('payment_product_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PeripheralBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('video_link', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('public', models.BooleanField(default=False)),
                ('surgery_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmodels.surgerytype')),
            ],
        ),
        migrations.AddField(
            model_name='surgerytype',
            name='surgical_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmodels.surgicalarea'),
        ),
    ]
