# Generated by Django 5.0.1 on 2024-05-14 16:33

import appmodels.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmodels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalconfig',
            name='stripe_public_key',
            field=models.CharField(default='pk_test_51NgWGLER8UMbFaDxEOVox7rrpA2ldKYkmoOAgGdiOAAMslvcK8yDusoU2v3nzqUHydket9nmWBKVCZSZgLiATV7k00YG5HnBio', max_length=200),
        ),
        migrations.AddField(
            model_name='generalconfig',
            name='stripe_secret_key',
            field=models.CharField(default='sk_test_51NgWGLER8UMbFaDxas2HSvtfgfPPccJr0UztjBaWaa56wnVrF9zaZGLdai4twWJxxQqw8EmvQmUdbHUU3EVv8mxI00NwU1maSk', max_length=200),
        ),
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('HIDDEN', 'Hidden'), ('PAYMENT ERROR', 'Payment error'), ('CANCELLING', 'Cancelling'), ('CANCELED', 'Canceled')], default='INACTIVE', max_length=30),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='generalconfig',
            name='smtp_email_account',
            field=models.CharField(default='no-reply@tfgibex.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='generalconfig',
            name='smtp_password',
            field=models.CharField(default='app2024ERB/', max_length=100),
        ),
        migrations.AlterField(
            model_name='generalconfig',
            name='smtp_server',
            field=models.CharField(default='smtp.servidor-correo.net', max_length=100),
        ),
        migrations.AlterField(
            model_name='peripheralblock',
            name='description',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_product_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='surgerytype',
            name='description',
            field=models.CharField(blank=True, default='', max_length=6000, null=True),
        ),
        migrations.AlterField(
            model_name='surgicalarea',
            name='description',
            field=models.CharField(blank=True, default='', max_length=6000, null=True),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=appmodels.models.upload_to_periphera_block_pics)),
                ('title', models.CharField(default='', max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=6000, null=True)),
                ('peripheral_block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='appmodels.peripheralblock')),
            ],
        ),
    ]
