# Generated by Django 5.0.1 on 2025-09-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmodels', '0003_alter_subscription_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalconfig',
            name='paypal_account_email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='generalconfig',
            name='paypal_client_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='generalconfig',
            name='paypal_secret_key',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='generalconfig',
            name='stripe_public_key',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='generalconfig',
            name='stripe_secret_key',
            field=models.CharField(default='', max_length=200),
        ),
    ]
