# Generated by Django 5.0.1 on 2025-09-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmodels', '0008_rename_image_peripheral_block_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='bolsa',
        ),
        migrations.AddField(
            model_name='empresa',
            name='bolsas',
            field=models.ManyToManyField(related_name='empresas', to='appmodels.bolsa'),
        ),
    ]
