# Generated by Django 5.0.1 on 2025-09-28 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmodels', '0010_empresa_mercado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='mercado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to='appmodels.mercado'),
        ),
    ]
