# Generated by Django 5.0.1 on 2025-09-28 22:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmodels', '0011_alter_empresa_mercado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True, max_length=1000, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
                ('source_url', models.URLField(blank=True, max_length=500, null=True)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('tags', models.CharField(blank=True, max_length=500, null=True)),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], default='neutral', max_length=20)),
                ('is_premium', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=True)),
                ('api_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('api_source', models.CharField(blank=True, max_length=100, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to='appmodels.empresa')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-published_date'],
            },
        ),
    ]
