# Generated by Django 5.0.1 on 2025-09-28 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmodels', '0012_noticia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='sentiment',
        ),
    ]
