# Generated by Django 5.0.1 on 2025-09-28 22:26

import appmodels.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmodels', '0013_remove_noticia_sentiment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='image_url',
        ),
        migrations.AddField(
            model_name='noticia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=appmodels.models.upload_to_noticia_pics),
        ),
    ]
