# Generated by Django 5.0.1 on 2025-10-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmodels', '0014_remove_noticia_image_url_noticia_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='video_link',
        ),
        migrations.AddField(
            model_name='noticia',
            name='video_link',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
