# Generated by Django 5.0.1 on 2025-10-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmodels', '0015_remove_empresa_video_link_noticia_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='payment_method',
            field=models.CharField(choices=[('Free', 'Gratis'), ('Paypal', 'Paypal'), ('Cash', 'Efectivo'), ('Bank transfer', 'Transferencia bancaria'), ('Other', 'Otro')], default='Free', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activa'), ('PENDING', 'Pendiente'), ('HIDDEN', 'Oculta'), ('PAYMENT ERROR', 'Error de pago'), ('CANCELLING', 'Cancelando'), ('CANCELED', 'Cancelada')], default='INACTIVE', max_length=30),
        ),
    ]
