# Generated by Django 5.0.1 on 2025-10-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmodels', '0016_alter_subscription_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='is_premium',
        ),
        migrations.AddField(
            model_name='bolsa',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
