# Generated by Django 5.0.1 on 2025-10-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmodels', '0017_remove_noticia_is_premium_bolsa_is_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='interval_unit',
            field=models.CharField(choices=[('Y', 'Año'), ('M', 'Mes'), ('W', 'Semana')], default='M', max_length=3),
        ),
    ]
