# Generated by Django 5.0.1 on 2024-03-30 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appmodels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('details', models.TextField(blank=True)),
                ('ip', models.CharField(default='', max_length=20)),
                ('continent', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('region', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
                ('postal', models.CharField(default='', max_length=20)),
                ('lat', models.CharField(default='', max_length=20)),
                ('lng', models.CharField(default='', max_length=20)),
                ('item', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('details', models.TextField(blank=True)),
                ('ip', models.CharField(default='', max_length=20)),
                ('continent', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('region', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
                ('postal', models.CharField(default='', max_length=20)),
                ('lat', models.CharField(default='', max_length=20)),
                ('lng', models.CharField(default='', max_length=20)),
                ('payment_gateway', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='appmodels.product')),
                ('receptor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrackingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('details', models.TextField(blank=True)),
                ('ip', models.CharField(default='', max_length=20)),
                ('continent', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('region', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
                ('postal', models.CharField(default='', max_length=20)),
                ('lat', models.CharField(default='', max_length=20)),
                ('lng', models.CharField(default='', max_length=20)),
                ('has_active_subscription', models.BooleanField(default=False)),
                ('peripheral_block', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='appmodels.peripheralblock')),
                ('surgery_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='appmodels.surgerytype')),
                ('surgical_area', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='appmodels.surgicalarea')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('details', models.TextField(blank=True)),
                ('ip', models.CharField(default='', max_length=20)),
                ('continent', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('region', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
                ('postal', models.CharField(default='', max_length=20)),
                ('lat', models.CharField(default='', max_length=20)),
                ('lng', models.CharField(default='', max_length=20)),
                ('change_by_admin', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
