# Generated by Django 5.0.1 on 2024-05-15 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmodels', '0003_alter_subscription_user'),
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionlog',
            name='payload',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subscriptionlog',
            name='payment_gateway_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subscriptionlog',
            name='subscription',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='appmodels.subscription'),
        ),
    ]
