# Generated by Django 5.0.1 on 2024-05-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_subscriptionlog_payload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionlog',
            name='payload',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionlog',
            name='payment_gateway_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
